version: '3.2'

services:

  frontend:
    container_name: 'test-sql-frontend'
    build: frontend
    ports:
      - '80:80'
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    environment:
      - PHP_ENABLE_XDEBUG=1
      - PHP_IDE_CONFIG='serverName=frontend'
      - ANOTHER_SYSTEM_URL=https://example.com/api
      - ANOTHER_SYSTEM_USER=user
      - ANOTHER_SYSTEM_PASSWORD=password
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    container_name: 'test-sql-postgres'
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_DB=yii2advanced
      - POSTGRES_USER=yii2advanced
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
